const articleActionTypes = {
  GET_ARTICLES_SUCCESS: 'GET_ARTICLES_SUCCESS',
  GET_ARTICLES_FAIL: 'GET_ARTICLES_FAIL',
  GET_ARTICLES_BEGIN: 'GET_ARTICLES_BEGIN',
  GET_SINGLE_ARTICLE: 'GET_SINGLE_ARTICLE',
  ARTICLE_NOT_FOUND: 'ARTICLE_NOT_FOUND'
};
export default articleActionTypes;
